{"name": "test_login_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <test_feature_story.TestLogin object at 0x00000000037670D0>\n\n    @allure.story('密码缺失')\n    def test_login_failure(self):\n        # with allure.step  标记测试步骤\n        with allure.step('点击用户名'):\n            print('输入用户名')\n        with allure.step('点击密码'):\n            print('输入密码')\n        print('点击登录')\n        with allure.step('点击登录之后登录失败'):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:37: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1616503508867, "stop": 1616503508868}, {"name": "点击密码", "status": "passed", "start": 1616503508868, "stop": 1616503508868}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\PycharmProjects\\hogwarts\\test_feature_story.py\", line 37, in test_login_failure\n    assert '1' == 1\n"}, "start": 1616503508868, "stop": 1616503508869}], "attachments": [{"name": "stdout", "source": "a398fdae-3505-40bb-9d2c-89f148d9026e-attachment.txt", "type": "text/plain"}], "start": 1616503508866, "stop": 1616503508870, "uuid": "63598cff-a48b-422f-94c6-30d634de9b0c", "historyId": "a58c5550e5c40eb80abda2e84e87077a", "testCaseId": "a0fb827149424dbc77d431148fe9f888", "fullName": "test_feature_story.TestLogin#test_login_failure", "labels": [{"name": "story", "value": "密码缺失"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "PC-201705071250"}, {"name": "thread", "value": "7492-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}